version: "3.7"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - case-study
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=casestudy
  app:
    depends_on:
      - db
    image: case-study
    ports:
      - "8080:8080"
    networks:
      - case-study
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db:3306/casestudy",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "12345"
      }'

networks:
  case-study:

volumes:
  mysql-volume:
    external: true
    name: mysql-volume