create table movies(
    --id integer not null primary key,
    id integer not null generated always as identity primary key,
    title varchar(300) not null,
    publishyear varchar(20),
    rated varchar(20),
    released date,
    runtime varchar(20),
    genre varchar(100),
    director varchar(300) not null,
    writer varchar(300) not null,
    actors varchar(300),
    plot varchar(300),
    language varchar(100),
    country varchar(100),
    awards varchar(100),
    poster varchar(200),
    metascore integer,
    imdbrating double not null,
    imdbvotes integer,
    imdbID varchar(20),
    type varchar(20) not null,
    totalseasons integer,
    comingsoon boolean
);